services:

  app:
    build: .
    container_name: php_app
    restart: always
    ports:
      - "8080:80"  
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - FRONTEND_URL=${FRONTEND_URL}

  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    links:
      - app
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    entrypoint: >+
      sh -c 'if [ "$ENVIRONMENT" = "production" ]; then
              cp /etc/nginx/conf.d/nginx.prod.conf /etc/nginx/nginx.conf;
             elif [ "$ENVIRONMENT" = "testing" ]; then
              cp /etc/nginx/conf.d/nginx.test.conf /etc/nginx/nginx.conf;
             else
              cp /etc/nginx/conf.d/nginx.dev.conf /etc/nginx/nginx.conf;
             fi &&
             nginx -g "daemon off;"'

volumes:
  db_data:
